### ISSUE TITLE
Standalone controller configuration lacks reset and filter circuitry

### ISSUE THREAD

**Issue by gnbl** [lgbeno/BLDC-Booster#2]
Not an issue for me, but be aware: the schematic and layout allow for a dedicated controller to be populated on the board, obviously considered for use without Launchpad. However, the supply voltage is not equipped with blocking caps (e.g. 100 nF) and the RST pin does not have a pull-up resistor. So, this will probably not work stand-alone.

**Comment by lgbeno** [comment]
Thanks for the feedback, I am aware of the RST, I made that mistake and needed to bodge one in.  As you can probably tell, the project hasn't been updated in awhile, I've pretty much moved on to other things but still like this one and have plenty of spare boards laying around.

WRT Blocking caps are you referring to supply decoupling?  That's probably a good idea.  So far in my testing, the design gets by with C2 and C3.

One change that I do make is lowering the base resistance of R3, R11 and R19 to give the driver a little more current to charge the larger PMOS gate capacitance.
